[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"
